import time

def generate_report(analyzed_papers, events):
    """
    Generates a Markdown report from the analyzed data.
    """
    date_str = time.strftime("%Y-%m-%d")
    filename = f"weekly_report_{date_str}.md"
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"# 🔬 The Curious Scout Report: {date_str}\n")
        f.write(f"Generated by AI Science Agent\n\n")
        
        # --- SECTION 1: PAPERS ---
        f.write(f"## 📄 Top Papers Found ({len(analyzed_papers)})\n\n")
        
        if not analyzed_papers:
            f.write("_No relevant papers found in this search window._\n\n")
        
        # Sort by Tier (Tier 1 first)
        # Note: We handle cases where 'tier' might be None or missing
        analyzed_papers.sort(key=lambda x: x.get('tier') or 99)
        
        for p in analyzed_papers:
            tier = p.get('tier', 'N/A')
            f.write(f"### {p['title']}\n")
            f.write(f"**Venue:** {p.get('venue')} | **Tier:** {tier}\n\n")
            
            analysis = p.get('analysis', {})
            if not analysis:
                f.write("> _No detailed analysis available._\n")
            
            if tier == 1:
                f.write(f"> **💡 Innovation:** {analysis.get('innovation', 'N/A')}\n")
                f.write(f"> **⚙️ Process:** {analysis.get('process', 'N/A')}\n")
                f.write(f"> **🔑 Insight:** {analysis.get('insight', 'N/A')}\n")
            elif tier == 2:
                f.write(f"> **🚀 Tech:** {analysis.get('tech', 'N/A')}\n")
                f.write(f"> **🔗 Relevance:** {analysis.get('relevance', 'N/A')}\n")
            elif tier == 3:
                 f.write(f"> **📝 Gist:** {analysis.get('gist', 'N/A')}\n")
            
            url = p.get('url')
            if url:
                f.write(f"\n[Read Paper]({url})\n")
            
            f.write("\n---\n")

        # --- SECTION 2: EVENTS ---
        f.write("\n## 🌍 Upcoming Events\n\n")
        if not events:
            f.write("_No events found or search was skipped._\n")
        
        for event in events:
            f.write(f"### {event.get('title', 'Unknown Event')}\n")
            f.write(f"**Date:** {event.get('date', 'TBD')} | **Location:** {event.get('location', 'Online')}\n")
            desc = event.get('description', '')
            if desc:
                f.write(f"_{desc}_\n")
            f.write("\n")

    return filename